name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
#   nightly build
    - cron: "26 20 * * *"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://2ccd-2405-201-a808-70b8-64aa-4d06-690d-aac4.ngrok-free.app/
        username: ${{ secrets.NXRM_USER }}
        password: ${{ secrets.NXRM_PASSWORD }}
        format: raw
        repository: raw-github-action-test
        coordinates: directory=nexus-repo-github-action-test-rawrepodir
        assets: filename=gh-action-test
        filename: ./gh-action-test
